/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsDothtmlRouteImport } from './routes/terms[.]html'
import { Route as TermsDeDothtmlRouteImport } from './routes/terms-de[.]html'
import { Route as SupportDothtmlRouteImport } from './routes/support[.]html'
import { Route as PrivacyDothtmlRouteImport } from './routes/privacy[.]html'
import { Route as PrivacyDeDothtmlRouteImport } from './routes/privacy-de[.]html'
import { Route as KampagneDothtmlRouteImport } from './routes/kampagne[.]html'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GuidelinesDothtmlRouteImport } from './routes/guidelines[.]html'
import { Route as GuidelinesDeDothtmlRouteImport } from './routes/guidelines-de[.]html'
import { Route as DatenschutzDothtmlRouteImport } from './routes/datenschutz[.]html'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'

const TermsDothtmlRoute = TermsDothtmlRouteImport.update({
  id: '/terms.html',
  path: '/terms.html',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsDeDothtmlRoute = TermsDeDothtmlRouteImport.update({
  id: '/terms-de.html',
  path: '/terms-de.html',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportDothtmlRoute = SupportDothtmlRouteImport.update({
  id: '/support.html',
  path: '/support.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyDothtmlRoute = PrivacyDothtmlRouteImport.update({
  id: '/privacy.html',
  path: '/privacy.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyDeDothtmlRoute = PrivacyDeDothtmlRouteImport.update({
  id: '/privacy-de.html',
  path: '/privacy-de.html',
  getParentRoute: () => rootRouteImport,
} as any)
const KampagneDothtmlRoute = KampagneDothtmlRouteImport.update({
  id: '/kampagne.html',
  path: '/kampagne.html',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesDothtmlRoute = GuidelinesDothtmlRouteImport.update({
  id: '/guidelines.html',
  path: '/guidelines.html',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesDeDothtmlRoute = GuidelinesDeDothtmlRouteImport.update({
  id: '/guidelines-de.html',
  path: '/guidelines-de.html',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzDothtmlRoute = DatenschutzDothtmlRouteImport.update({
  id: '/datenschutz.html',
  path: '/datenschutz.html',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JoinRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz.html': typeof DatenschutzDothtmlRoute
  '/guidelines-de.html': typeof GuidelinesDeDothtmlRoute
  '/guidelines.html': typeof GuidelinesDothtmlRoute
  '/join': typeof JoinRouteWithChildren
  '/kampagne.html': typeof KampagneDothtmlRoute
  '/privacy-de.html': typeof PrivacyDeDothtmlRoute
  '/privacy.html': typeof PrivacyDothtmlRoute
  '/support.html': typeof SupportDothtmlRoute
  '/terms-de.html': typeof TermsDeDothtmlRoute
  '/terms.html': typeof TermsDothtmlRoute
  '/join/$slug': typeof JoinSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz.html': typeof DatenschutzDothtmlRoute
  '/guidelines-de.html': typeof GuidelinesDeDothtmlRoute
  '/guidelines.html': typeof GuidelinesDothtmlRoute
  '/join': typeof JoinRouteWithChildren
  '/kampagne.html': typeof KampagneDothtmlRoute
  '/privacy-de.html': typeof PrivacyDeDothtmlRoute
  '/privacy.html': typeof PrivacyDothtmlRoute
  '/support.html': typeof SupportDothtmlRoute
  '/terms-de.html': typeof TermsDeDothtmlRoute
  '/terms.html': typeof TermsDothtmlRoute
  '/join/$slug': typeof JoinSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz.html': typeof DatenschutzDothtmlRoute
  '/guidelines-de.html': typeof GuidelinesDeDothtmlRoute
  '/guidelines.html': typeof GuidelinesDothtmlRoute
  '/join': typeof JoinRouteWithChildren
  '/kampagne.html': typeof KampagneDothtmlRoute
  '/privacy-de.html': typeof PrivacyDeDothtmlRoute
  '/privacy.html': typeof PrivacyDothtmlRoute
  '/support.html': typeof SupportDothtmlRoute
  '/terms-de.html': typeof TermsDeDothtmlRoute
  '/terms.html': typeof TermsDothtmlRoute
  '/join/$slug': typeof JoinSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz.html'
    | '/guidelines-de.html'
    | '/guidelines.html'
    | '/join'
    | '/kampagne.html'
    | '/privacy-de.html'
    | '/privacy.html'
    | '/support.html'
    | '/terms-de.html'
    | '/terms.html'
    | '/join/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz.html'
    | '/guidelines-de.html'
    | '/guidelines.html'
    | '/join'
    | '/kampagne.html'
    | '/privacy-de.html'
    | '/privacy.html'
    | '/support.html'
    | '/terms-de.html'
    | '/terms.html'
    | '/join/$slug'
  id:
    | '__root__'
    | '/'
    | '/datenschutz.html'
    | '/guidelines-de.html'
    | '/guidelines.html'
    | '/join'
    | '/kampagne.html'
    | '/privacy-de.html'
    | '/privacy.html'
    | '/support.html'
    | '/terms-de.html'
    | '/terms.html'
    | '/join/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzDothtmlRoute: typeof DatenschutzDothtmlRoute
  GuidelinesDeDothtmlRoute: typeof GuidelinesDeDothtmlRoute
  GuidelinesDothtmlRoute: typeof GuidelinesDothtmlRoute
  JoinRoute: typeof JoinRouteWithChildren
  KampagneDothtmlRoute: typeof KampagneDothtmlRoute
  PrivacyDeDothtmlRoute: typeof PrivacyDeDothtmlRoute
  PrivacyDothtmlRoute: typeof PrivacyDothtmlRoute
  SupportDothtmlRoute: typeof SupportDothtmlRoute
  TermsDeDothtmlRoute: typeof TermsDeDothtmlRoute
  TermsDothtmlRoute: typeof TermsDothtmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms.html': {
      id: '/terms.html'
      path: '/terms.html'
      fullPath: '/terms.html'
      preLoaderRoute: typeof TermsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-de.html': {
      id: '/terms-de.html'
      path: '/terms-de.html'
      fullPath: '/terms-de.html'
      preLoaderRoute: typeof TermsDeDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support.html': {
      id: '/support.html'
      path: '/support.html'
      fullPath: '/support.html'
      preLoaderRoute: typeof SupportDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy.html': {
      id: '/privacy.html'
      path: '/privacy.html'
      fullPath: '/privacy.html'
      preLoaderRoute: typeof PrivacyDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-de.html': {
      id: '/privacy-de.html'
      path: '/privacy-de.html'
      fullPath: '/privacy-de.html'
      preLoaderRoute: typeof PrivacyDeDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kampagne.html': {
      id: '/kampagne.html'
      path: '/kampagne.html'
      fullPath: '/kampagne.html'
      preLoaderRoute: typeof KampagneDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines.html': {
      id: '/guidelines.html'
      path: '/guidelines.html'
      fullPath: '/guidelines.html'
      preLoaderRoute: typeof GuidelinesDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines-de.html': {
      id: '/guidelines-de.html'
      path: '/guidelines-de.html'
      fullPath: '/guidelines-de.html'
      preLoaderRoute: typeof GuidelinesDeDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz.html': {
      id: '/datenschutz.html'
      path: '/datenschutz.html'
      fullPath: '/datenschutz.html'
      preLoaderRoute: typeof DatenschutzDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof JoinRoute
    }
  }
}

interface JoinRouteChildren {
  JoinSlugRoute: typeof JoinSlugRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinSlugRoute: JoinSlugRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzDothtmlRoute: DatenschutzDothtmlRoute,
  GuidelinesDeDothtmlRoute: GuidelinesDeDothtmlRoute,
  GuidelinesDothtmlRoute: GuidelinesDothtmlRoute,
  JoinRoute: JoinRouteWithChildren,
  KampagneDothtmlRoute: KampagneDothtmlRoute,
  PrivacyDeDothtmlRoute: PrivacyDeDothtmlRoute,
  PrivacyDothtmlRoute: PrivacyDothtmlRoute,
  SupportDothtmlRoute: SupportDothtmlRoute,
  TermsDeDothtmlRoute: TermsDeDothtmlRoute,
  TermsDothtmlRoute: TermsDothtmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
